default_node = "127.0.0.1:9000"

[[my_keys]]
public = "keys/alice.pub.pem"
private = "keys/alice.priv.cbor"

[[contacts]]
name = "Bob"
address = "18VvDB8FnwU4symRpFSjbFoDJFyzQyHWVV"

[fee_config]
fee_type = "Percent"
value = 0.1
