[package]
name = "miner"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
btclib = { path = "../lib" }
clap = { version = "4.5.53", features = ["derive"] }
flume = "0.11.1"
tokio = { version = "1.48.0", features = ["full"] }
uuid = { version = "1", features = ["v4"] }
